os: linux
dist: xenial
language: elixir

cache:
  directories:
    - _build
    - deps
    - "${HOME}/bin"

env:
  - CAN_FAIL=false

jobs:
  allow_failures:
    env:
      - CAN_FAIL=true
      - VER_INFLUXDB=2.0.3
      - INFLUX_TOKEN=instream_test

  include:
    - stage: test
      elixir: 1.11.2
      otp_release: 23.0
      env:
        - CAN_FAIL=true
        - VER_INFLUXDB=2.0.3
        - INFLUX_TOKEN=instream_test
      before_install: |-
        if [ ! -x "${HOME}/bin/influxd" ]; then
          mkdir -p "${HOME}/bin"

          wget "https://dl.influxdata.com/influxdb/releases/influxdb2-${VER_INFLUXDB}_linux_amd64.tar.gz"
          tar -xzf "influxdb2-${VER_INFLUXDB}_linux_amd64.tar.gz"
          find influxdb2-* -name influxd -type f -exec mv {} "${HOME}/bin" \;
        fi
      before_script: |-
        function start_influxdb {
          nohup "${HOME}/bin/influxd" \
          >>./influxdb.stdout 2>>./influxdb.stderr &

          until curl -s -o /dev/null 'http://localhost:8086' 2>/dev/null; do
            sleep 1
          done
        }

        start_influxdb
        curl -XPOST http://localhost:8086/api/v2/setup -H 'accept: application/json' -d "{\"username\": \"instream_test\", \"password\": \"instream_test\", \"org\": \"instream_test\", \"bucket\": \"test_database\", \"token\": \"${INFLUX_TOKEN}\"}" -s -o /dev/null
      script: mix test --trace
      after_failure: |-
        echo '==> stdout <=='
        cat ./influxdb.stdout
        echo '==> stderr <=='
        cat ./influxdb.stderr
      after_script: ps | grep 'influxd' | grep -v 'grep' | awk '{ print $1 }' | xargs kill
