name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - elixir: '1.7.4'
            otp: '19.3'
            influxdb: '1.7.10'
          - elixir: '1.8.2'
            otp: '20.3'
            influxdb: '1.8.3'
          - elixir: '1.9.4'
            otp: '21.3'
            influxdb: '1.8.3'
          - elixir: '1.10.4'
            otp: '22.3'
            influxdb: '1.8.3'
          - elixir: '1.11.2'
            otp: '23.0'
            influxdb: '1.8.3'

    services:
      influxdb:
        image: influxdb:${{ matrix.influxdb }}
        env:
          INFLUXDB_HTTP_AUTH_ENABLED: true
          INFLUXDB_HTTP_FLUX_ENABLED: true
          INFLUXDB_ADMIN_USER: instream_test
          INFLUXDB_ADMIN_PASSWORD: instream_test
          INFLUXDB_USER: instream_guest
          INFLUXDB_USER_PASSWORD: instream_guest
          INFLUXDB_UDP_ENABLED: true
          INFLUXDB_UDP_BIND_ADDRESS: ':8089'
          INFLUXDB_UDP_DATABASE: test_database
          INFLUXDB_UDP_BATCH_SIZE: 1000
          INFLUXDB_UDP_BATCH_TIMEOUT: '1s'
          INFLUXDB_UDP_BATCH_PENDING: 5
        ports:
          - 8086:8086
          - 8089:8089/udp

    steps:
    - uses: actions/checkout@v2

    - name: setup
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: mix-cache
      uses: actions/cache@v1
      id: mix-cache
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

    - name: mix-deps
      if: steps.mix-cache.outputs.cache-hit != 'true'
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: test
      run: mix coveralls
